CREATE TABLE IF NOT EXISTS user
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(50) NOT NULL UNIQUE,
    login    varchar(30) NOT NULL UNIQUE,
    name     varchar(30),
    birthday date
);
CREATE TABLE IF NOT EXISTS mpa_rating
(
    rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name  varchar(30) NOT NULL,
    UNIQUE (mpa_name)
);
CREATE TABLE IF NOT EXISTS film
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(200),
    description  varchar(200),
    release_date date,
    duration     INTEGER,
    rating_id    INTEGER REFERENCES mpa_rating (rating_id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS film_like
(
    film_id INTEGER REFERENCES film (id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES user (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);
CREATE TABLE IF NOT EXISTS friends
(
    user_id   INTEGER REFERENCES user (id) ON DELETE CASCADE,
    friend_id INTEGER REFERENCES user (id) ON DELETE CASCADE,
    status    bool,
    PRIMARY KEY (user_id, friend_id)
);
CREATE TABLE IF NOT EXISTS genre
(
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  INTEGER REFERENCES film (id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genre (genre_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);
